### ISSUE TITLE
Drop support for Python2

### ISSUE THREAD

**Issue by ngosang** [qbittorrent/search-plugins#84]
Python2 support ends in 2019. https://pythonclock.org/

Changes in qBittorrent:
- [ ] Change version checker to show an error with Python < 3.x
- [ ] Remove nova2 code
- [ ] Include [requests](https://github.com/kennethreitz/requests) and [beautifulsoup4](https://github.com/wention/BeautifulSoup4) libraries (copy the source code) #53
- [ ] Improve / add new features in nova3 code
  - [ ] Download favicons from the URL included in each search-engine plugin. #42
  - [ ] Update nova3 plugins to use requests and beautifulsoup4 libraries
  - [ ] Update nova3 to allow future features like #45
  - [ ] Allow to disable plugins by default. E.g. Jackett needs configuration, and should be disabled by default.
  - [ ] Improve `download_files` method #33

Changes in search-plugins:
- [x] Keep nova2 plugins until they stop working
- [ ] Update nova3 plugins to use Python3 features (don't need to be backwards compatible anymore)
- [ ] Update nova3 plugins to use requests and beautifulsoup4 libraries
- [ ] Include search-engines favicons in this repository. #42
- [ ] Add favicon URL in each search-engine plugin #42
- [ ] Review unofficial plugins
- [ ] Update documentation

**Comment by ngosang** [comment]
@Chocobo1 Would you like to help me with the qBittorrent part? I can do most of the Python work and review your changes, but I will need some help with the C++ part.
There is no hurry, but I want to drop support before the end of the year. At that time most Linux distributions will have python3 as default version so the user don't have to worry about that...

**Comment by sledgehammer999** [comment]
With the recent minimum Qt version change (aka 5.9) I think we require fairly recent distros anyway. So personally I don't have a problem. The rest is up to you, since I am not using this feature.

**Comment by Chocobo1** [comment]
I'm only interested in dropping py2 support, can't say about the new features.

Just a reminder, the reason of supporting py2 is because of [macOS](https://github.com/qbittorrent/qBittorrent/issues/7005), so I think we can only drop it after the date expires not before.

**Comment by sledgehammer999** [comment]
>Just a reminder, the reason of supporting py2 is because of macOS

ohh I forgot about that...

**Comment by ngosang** [comment]
Related https://github.com/qbittorrent/qBittorrent/pull/7496 https://github.com/qbittorrent/qBittorrent/issues/7192

**Comment by Chocobo1** [comment]
I've opened PR https://github.com/qbittorrent/qBittorrent/pull/11813
Also I would expect search-plugins repo *not* drop py2 scripts *until* qbt has a new release containing changes in that PR.

**Comment by FranciscoPombal** [comment]
@ngosang python 2 stuff can now be dropped, https://github.com/qbittorrent/qBittorrent/pull/11813 has been merged and included in some official releases by now. Plugins that use it need to be updated for python 3 or removed.

**Comment by ngosang** [comment]
@FranciscoPombal Thanks for your notice. At this moment all official plugins are working in Python2 and Python3. There are still users who have older versions and the official Python 2 plugins still work. Since these definitions do not affect the new versions of qBittorrent I prefer to leave them a little longer until main distributions update the package at least.

@joseeloren @nicolasalonzo @darktohka @hannsen @imDMG @iordic Thank you for keeping the [unofficial list](https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins) updated.
Since `March 24th 2020 / v4.2.2` qBittorrent only supports Python3. From now, the Python 3 support is mandatory and the Python 2 is optional (Python2 is not required for new plugins of after updating an existing plugin). If you know any plugin that doesn't work with Python3, please move the plugin to a new table at the bottom called "Deprecated plugins" or something like that and reach the original author to update the plugin. Also try to add a more specific information about the version of Python used to test the plugin. Eg `Python 3.6` instead of `Python 3`. There are huge differences between 3.4 and 3.9.

**Comment by joseeloren** [comment]
@ngosang ,my plugins work with Python 3. Thank you!

I made a PR to autoupdate plugins. You can check it here:
issue: https://github.com/qbittorrent/qBittorrent/issues/12594
PR: https://github.com/qbittorrent/qBittorrent/pull/12469

**Comment by FranciscoPombal** [comment]
@ngosang 
> Since these definitions do not affect the new versions of qBittorrent I prefer to leave them a little longer until main distributions update the package at least.

Ubuntu 20.04 was just released with no python 2 by default, and `/usr/bin/python` is deprecated, but points to `/usr/bin/python3`, meaning the user has to go out of their way to use python 2 (which is technically still available in the repos, but just due to a very small number of packages). Other fixed release distros are in similar or better situations.

Meanwhile, there is no currently supported mainstream linux distro that _doesn't_ offer some kind of official python 3 release by default (I think RHEL 6 might be an exception to this, but it is on life support and I doubt we care about it anyway). Ubuntu 16.04 has python 3.5, for example.

There is no more official upstream support for python 2, meaning no more security and bug fixes. Furthermore, I should mention that the minimum supported python 3 version right now is python 3.5, and will soon be 3.6 (https://devguide.python.org/#status-of-python-branches). So, IMO new plugins/updates shouldn't be required to support python < 3.5 (and later on in 2020, <3.6).

**Comment by ngosang** [comment]
@joseeloren The others developers will take care. We have in the roadmap to remove the search plugins and use Jackett instead. Maybe you can help #121

@FranciscoPombal Are Python2 plugins causing any problem in qBittorrent? qBittorrent checks the Python version and download only the folder that match so shouldn't be any problem.
You are right about the distributions. Linux users worry me the least because they receive automatic updates from Python and qBittorrent. I am thinking more of Windows users with updates disabled. I am sure there are thousands.
The official plugins are compatible with Python 2.7 and Python 3.4 - 3.9. We have [automatic tests](https://github.com/qbittorrent/search-plugins/blob/master/.travis.yml). In few months I will remove the `nova2`.

**Comment by p060477** [comment]
hi
i'd like to know ,a simple clarification, is jackett needs to be -installed- for having the jackett plugin workin in qbittorrent 4.2.5..?
i ask cause the python needs is well clarified in qbittorrent installation if you want the search option..
but there is no warning about jackett to be installed...

**Comment by FranciscoPombal** [comment]
@p060477 

> hi
> i'd like to know ,a simple clarification, is jackett needs to be -installed- for having the jackett plugin workin in qbittorrent 4.2.5..?
> i ask cause the python needs is well clarified in qbittorrent installation if you want the search option..
> but there is no warning about jackett to be installed...

Please stop spamming multiple issues with questions that could be solved with a simple google search and are unrelated to the current topic. If you need further support please use the forum, IRC, or Discord. The issue tracker is for bug reports/feature requests and related discussion only.
